apiVersion: v1
kind: ConfigMap
metadata:
  name: hotel-app-config
  namespace: hotel-system
  labels:
    app.kubernetes.io/name: hotel-billing-system
data:
  SPRING_PROFILES_ACTIVE: "prod"
  HOTEL_NAME: "Grand Horizon Luxury Palace & Resort"
  HOTEL_ADDRESS: "100 Marine Bay Promenade, Mumbai, MH 400001"
  HOTEL_PHONE: "+91 (022) 5550-1999"
  HOTEL_EMAIL: "billing@grandhorizonresort.in"
  HOTEL_TAX_RATE: "12.0"
  HOTEL_CURRENCY_SYMBOL: "₹"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service.hotel-system.svc.cluster.local:5432/hotel_billing_db"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  JAVA_OPTS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/./urandom"
