apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hotel-billing-ingress
  namespace: hotel-system
  labels:
    app.kubernetes.io/name: hotel-billing-system
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: hotel-billing.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hotel-billing-service
                port:
                  number: 80
