apiVersion: v1
kind: Secret
metadata:
  name: hotel-db-secret
  namespace: hotel-system
  labels:
    app.kubernetes.io/name: hotel-billing-system
type: Opaque
stringData:
  POSTGRES_DB: "hotel_billing_db"
  POSTGRES_USER: "hotel_admin"
  POSTGRES_PASSWORD: "hotel_secure_password_2026"
  SPRING_DATASOURCE_USERNAME: "hotel_admin"
  SPRING_DATASOURCE_PASSWORD: "hotel_secure_password_2026"
